### ISSUE TITLE
sleepd not reporting version via either of --version or -V command line option

### ISSUE THREAD

**Issue by SlySven** [lnslbrty/sleepd#1]
I just wanted to find out what the version of this program was - because I noticed that it seemed to have grabbed half of the memory of my Laptop!

However invoking the program with `sudo sleepd --version` and `sudo sleepd -V` just started up extra copies without doing what I would have expected (and then exiting) - though after seeing what the `-h`  option produced I now see why.  It is a pity that `-v` has already been assigned for verbose output mode... :wink:

**Comment by utoni** [comment]
Your are probably using the debian shipped version of sleepd which is **not** based on my fork. In fact it is based on Joey Hess' abandoned project.
